apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  deployment: kuadrant-qe-pipeline

resources:
  - ../tasks/
  - ../tasks/deploy/
  - ../tasks/infra/
  - ../tasks/provision-install-test/
  - pipeline.yaml
  - provision-install-test-pipeline.yaml
  - provision-upgrade-test-pipeline.yaml
  - aro-provision-install-test-pipeline.yaml
