apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: delete-rosa
spec:
  description: Delete ROSA cluster
  params:
    - default: kua-rosa-credentials
      description: Name of secret that contains IAM user credentials
      name: aws-credentials
      type: string
    - default: kua-ocm-stage-client-credentials
      description: Name of secret that contains client ID and client secret to log into OCM org
      name: ocm-credentials
      type: string
    - default: staging
      description: 'What OCM instance to use, either ''staging'' or ''production'''
      name: ocm-instance
      type: string
    - description: ROSA cluster ID that is to be deleted
      name: cluster-id
      type: string
  tasks:
    - name: rosa-login
      params:
        - name: ocm-instance
          value: $(params.ocm-instance)
        - name: ocm-credentials
          value: $(params.ocm-credentials)
        - name: region
          value: us-east-1 # region does not matter for ROSA cluster removal
        - name: aws-credentials
          value: $(params.aws-credentials)
      taskRef:
        kind: Task
        name: rosa-login
      workspaces:
        - name: shared-workspace
    - name: delete-rosa
      params:
        - name: cluster-id
          value: $(params.cluster-id)
        - name: aws-credentials
          value: $(params.aws-credentials)
        - name: region
          value: us-east-1 # region does not matter for ROSA cluster removal
      taskRef:
        kind: Task
        name: delete-rosa
      runAfter:
        - rosa-login
      workspaces:
        - name: shared-workspace
  workspaces:
    - name: shared-workspace
