apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  deployment: kuadrant-qe-pipeline-infra

resources:
  - ../tasks/infra/
  - osd-aws-pipeline.yaml
  - delete-osd-pipeline.yaml
  - osd-gcp-pipeline.yaml
