apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: nightly-cron-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: nightly-kuadrant-trigger
      bindings:
        - name: kube-api
          value: https://api.kuadrant.example.io:6443
        - name: project
          value: kuadrant
        - name: make-target
          value: all
        - name: additional-env
          value: ""
        - name: launch-name
          value: nightly
        - name: rp-project
          value: nightly-testsuite
      template:
        spec:
          params:
            - name: kube-api
            - name: project
            - name: make-target
            - name: additional-env
            - name: launch-name
            - name: rp-project
          resourcetemplates:
            - apiVersion: tekton.dev/v1beta1
              kind: PipelineRun
              metadata:
                generateName: nightly-$(tt.params.make-target)-
              spec:
                pipelineRef:
                  name: nightly-pipeline
                params:
                  - name: kube-api
                    value: $(tt.params.kube-api)
                  - name: project
                    value: $(tt.params.project)
                  - name: make-target
                    value: $(tt.params.make-target)
                  - name: additional-env
                    value: $(tt.params.additional-env)
                  - name: launch-name
                    value: $(tt.params.launch-name)
                  - name: rp-project
                    value: $(tt.params.rp-project)
                workspaces:
                  - name: shared-workspace
                    volumeClaimTemplate:
                      spec:
                        accessModes:
                          - ReadWriteOnce
                        resources:
                          requests:
                            storage: 10Mi
