apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  deployment: kuadrant-qe-pipeline-nightly

resources:
  - eventlistener.yaml
  - trigger-nightly-cronjob.yaml
  - ../tasks/
  - pipeline.yaml
