apiVersion: batch/v1
kind: CronJob
metadata:
  name: trigger-nightly-pipeline
spec:
  schedule: "0 5 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pipeline
          containers:
            - name: trigger-nightly-pipeline
              image: quay.io/curl/curl:latest
              command: ["/bin/sh", "-cx"]
              args: ["curl -X POST --data {} el-nightly-cron-listener.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local:8080"]
          restartPolicy: Never
