apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: nightly-trigger-binding
spec:
  params:
    - name: kube-api
      value: https://api.kuadrant.example.io:6443
    - name: project
      value: kuadrant
    - name: make-target
      value: $(body.make-target)
    - name: launch-name
      value: nightly
    - name: rp-project
      value: nightly-testsuite
