apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: deploy-mcp-gateway
spec:
  params:
# cluster
  - description: API URL of the Openshift cluster
    name: kube-api
    type: string
  - description: Secret name with cluster credentials
    name: cluster-credentials
    type: string
    default: openshift-pipelines-credentials
# Kuadrant
  - description: Deploy Kuadrant via Helm before installing MCP Gateway
    name: deploy-kuadrant
    type: string
    default: "true"
  - description: Kuadrant image url
    name: kuadrant-catalog-image
    type: string
    default: ""
  - description: Kuadrant image channel. Can be 'preview' for nightlies and 'stable' for releases
    name: channel
    type: string
    default: stable
  - description: Kuadrant operator name. 'kuadrant-operator' or 'rhcl-operator'
    name: operator-name
    type: string
    default: rhcl-operator
  - description: Additional flags for helm install command, example '--set=kuadrant.installPlanApproval=Manual --set=kuadrant.startingCSV=kuadrant-operator.v1.2.0'
    name: additional-helm-flags
    type: string
    default: ""
  - description: Additional flags for tools helm, example '--set=tools.keycloak.keycloakProvider=deployment --set=tools.valkey.enable=false'"
    name: additional-helm-tools-flags
    type: string
    default: ""
# Gateway API
  - description: Istio provider (ossm3, ocp); 'ossm3' (Service Mesh installed via OLM), 'ocp' (Istio managed by Gateway API (GatewayClass CR), available for OCP v4.19+)
    name: istio-provider
    type: string
    default: ocp
  - description: GatewayAPI CRD version. [v1.2.1, v1.3.0, v1.4.0] available; leave empty if installing on Openshift 4.19+.
    name: gateway-crd
    type: string
    default: ""
# MCP Gatweay
  - description: Deploy MCP Gateway before running the MCP Gateway tests
    name: deploy-mcp-gateway
    type: string
    default: "true"
  - description: MCP Gateway git repository URL
    name: mcp-gateway-repo-url
    type: string
    default: https://github.com/Kuadrant/mcp-gateway.git
  - description: MCP Gateway git revision (branch, tag, or commit) to checkout
    name: mcp-gateway-revision
    type: string
    default: main
  - description: MCP Controller catalog image
    name: mcp-controller-catalog-image
    type: string
    default: ghcr.io/kuadrant/mcp-controller-catalog:main
# Conformance tests
  - description: MCP conformance test suite version
    name: conformance-version
    type: string
    default: "0.1.15"
  tasks:
  - name: kubectl-login
    params:
    - name: kube-api
      value: $(params.kube-api)
    - name: testsuite-image
      value: quay.io/kuadrant/testsuite-pipelines-tools:latest
    - name: cluster-credentials
      value: $(params.cluster-credentials)
    taskRef:
      kind: Task
      name: kubectl-login
    workspaces:
    - name: shared-workspace
      workspace: shared-workspace
  - name: helm-deploy
    retries: 3
    runAfter:
    - kubectl-login
    when:
      - input: $(params.deploy-kuadrant)
        operator: in
        values: ["true"]
    taskRef:
      kind: Task
      name: helm-deploy
    params:
      - name: index-image
        value: $(params.kuadrant-catalog-image)
      - name: channel
        value: $(params.channel)
      - name: istio-provider
        value: $(params.istio-provider)
      - name: gateway-crd
        value: $(params.gateway-crd)
      - name: operator-name
        value: $(params.operator-name)
      - name: kubeconfig-path
        value: $(tasks.kubectl-login.results.kubeconfig-path)
      - name: additional-helm-flags
        value: $(params.additional-helm-flags)
      - name: additional-helm-tools-flags
        value: $(params.additional-helm-tools-flags)
    workspaces:
    - name: shared-workspace
      workspace: shared-workspace
  - name: clone-mcp-gateway-repo
    runAfter:
    - kubectl-login
    - helm-deploy
    taskRef:
      kind: Task
      name: clone-repo
    params:
      - name: repo-url
        value: $(params.mcp-gateway-repo-url)
      - name: revision
        value: $(params.mcp-gateway-revision)
      - name: dest-dir
        value: mcp-gateway
    workspaces:
    - name: shared-workspace
      workspace: shared-workspace
  - name: install-mcp-gateway
    runAfter:
    - clone-mcp-gateway-repo
    when:
      - input: $(params.deploy-mcp-gateway)
        operator: in
        values: ["true"]
    taskRef:
      kind: Task
      name: install-mcp-gateway
    params:
      - name: kubeconfig-path
        value: $(tasks.kubectl-login.results.kubeconfig-path)
      - name: catalog-image
        value: $(params.mcp-controller-catalog-image)
      - name: istio-provider
        value: $(params.istio-provider)
    workspaces:
    - name: shared-workspace
      workspace: shared-workspace
  - name: run-conformance-tests
    runAfter:
    - install-mcp-gateway
    taskRef:
      kind: Task
      name: run-conformance-tests
    params:
      - name: kubeconfig-path
        value: $(tasks.kubectl-login.results.kubeconfig-path)
      - name: conformance-version
        value: $(params.conformance-version)
    workspaces:
    - name: shared-workspace
      workspace: shared-workspace
  workspaces:
  - name: shared-workspace
