apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cluster-secret-cleanup
spec:
  description: Remove the cluster credentials secret
  params:
    - name: cluster-name
      type: string
  steps:
    - computeResources:
        limits:
          cpu: '100m'
          memory: 64Mi
      env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      image: quay.io/kuadrant/testsuite-pipelines-tools:latest
      imagePullPolicy: Always
      name: cluster-cleanup
      script: |
        #!/usr/bin/env bash
        set -evo pipefail

        kubectl delete --ignore-not-found secret "$(params.cluster-name)-credentials" -n ${NAMESPACE}

