apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: get-cluster-id
spec:
  description: Retrieve OCM/HCC cluster ID
  params:
    - name: cluster-name
      type: string
  results:
    - name: cluster-id
      description: Cluster ID used in OCM/HCC
  steps:
    - computeResources:
        limits:
          cpu: '100m'
          memory: 64Mi
      image: quay.io/kuadrant/testsuite-pipelines-tools:latest
      imagePullPolicy: Always
      name: get-cluster-id
      script: |
        #!/usr/bin/env bash
        set -evo pipefail

        # Use ocm.json created by ocm-login Task
        export OCM_CONFIG=$(workspaces.shared-workspace.path)/ocm.json

        # Include cluster ID in results
        if ! cluster_id=$(ocm get /api/clusters_mgmt/v1/clusters --parameter search="name like '$(params.cluster-name)'" | jq -e -r '.items[0].id'); then
            echo "Cluster '$(params.cluster-name)' not found."
            exit 1
        fi

        echo -n $cluster_id | tee $(results.cluster-id.path)
  workspaces:
    - name: shared-workspace

