apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ocm-login-task.yaml
  - provision-osd-aws-task.yaml
  - wait-till-osd-is-ready-task.yaml
  - get-osd-credentials-task.yaml
  - delete-osd-task.yaml
  - wait-till-osd-is-deleted-task.yaml
