apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: prepare-for-rhcl-rc-install
spec:
  description: Prepare for RHCL RC installation
  params:
    - name: kubeconfig-path
      type: string
  steps:
    - computeResources:
        limits:
          cpu: '200m'
          memory: 256Mi
      env:
        - name: KUBECONFIG
          value: $(params.kubeconfig-path)
        - name: ADDITIONAL_AUTH_ENTRIES
          valueFrom:
            secretKeyRef:
              key: additional-auth-entries
              name: additional-auth-entries
      image: quay.io/kuadrant/testsuite-pipelines-tools:latest
      imagePullPolicy: Always
      name: prepare-for-rhcl-rc-install
      script: |
        #!/usr/bin/env bash
        set -evo pipefail

        # Creates ICSP that allow to mirroring to brew
        kubectl apply -f -<<EOF
            apiVersion: operator.openshift.io/v1alpha1
            kind: ImageContentSourcePolicy
            metadata:
              name: errata-from-brew
            spec:
              repositoryDigestMirrors:
              - mirrors:
                - brew.registry.redhat.io/rh-osbs
                source: registry-proxy.engineering.redhat.com/rh-osbs
              - mirrors:
                  - brew.registry.redhat.io/rhcl-1
                source: registry.redhat.io/rhcl-1
        EOF

        # update global pull secret
        kubectl get secret/pull-secret -n openshift-config -o jsonpath='{.data.\.dockerconfigjson}' | base64 -d > current-auths.json

        jq --argjson new_auths "{${ADDITIONAL_AUTH_ENTRIES}}" '.auths += $new_auths' current-auths.json > updated-auths.json

        UPDATED_AUTHS_JSON=$(base64 -w0 < updated-auths.json)

        patch_status=$(kubectl patch secret pull-secret -n openshift-config --type=merge -p='{"data":{".dockerconfigjson":"'"$UPDATED_AUTHS_JSON"'"}}')

        # wait for global pull secret change to get applied on all nodes
        if [[ "$patch_status" != *"no change"* ]]; then
            kubectl wait --for=condition=Updating --timeout=120s mcp/worker
            kubectl wait --for=condition=Updated --timeout=1800s mcp/master
            kubectl wait --for=condition=Updated --timeout=1200s mcp/worker
            update_finished=$(kubectl get mcp -o json | jq -r '([ .items[] |
                select(
                  (.status.conditions[] | select(.type=="Updated").status == "True") and
                  (.status.conditions[] | select(.type=="Updating").status == "False") and
                  (.status.conditions[] | select(.type=="Degraded").status == "False")
                )] | length) == (.items | length)'
            )
            if [[ "$update_finished" == "true" ]]; then
                echo "Global pull secret change has been successfully applied to all nodes"
            else
                echo "Global pull secret change has not been applied to all nodes in time"
                exit 1
            fi
        fi
  workspaces:
    - name: shared-workspace

