apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: infra-osd-gcp
spec:
  description: Provision OSD on GCP
  params:
    - default: kua-gcp-credentials
      description: Name of secret that contains JSON credentials for GCP (osd-ccs-admin user)
      name: gcp-credentials
      type: string
    - default: kua-ocm-stage-client-credentials
      description: Name of secret that contains client ID and client secret to log into OCM org
      name: ocm-credentials
      type: string
    - default: staging
      description: 'What OCM instance to use, either ''staging'' or ''production'''
      name: ocm-instance
      type: string
    - default: kua-gcp-test
      description: OSD cluster name
      name: cluster-name
      type: string
    - default: '--provider=gcp --ccs --channel-group=stable --compute-machine-type=n2-standard-4 --compute-nodes=3 --enable-autoscaling=false --multi-az=false --region=us-east1 --version=4.17.12 --machine-cidr=10.0.0.0/16 --pod-cidr=10.128.0.0/14 --service-cidr=172.36.0.0/16 --host-prefix=23'
      description: 'Flags to be used for `ocm create cluster [:osd-name]` command. Do not provide --service-account-file flag here.'
      name: create-cmd-flags
      type: string
  tasks:
    - name: ocm-login
      params:
        - name: ocm-instance
          value: $(params.ocm-instance)
        - name: ocm-credentials
          value: $(params.ocm-credentials)
      taskRef:
        kind: Task
        name: ocm-login
      workspaces:
        - name: shared-workspace
    - name: provision-osd-gcp
      params:
        - name: gcp-credentials
          value: $(params.gcp-credentials)
        - name: create-cmd-flags
          value: $(params.create-cmd-flags)
        - name: cluster-name
          value: $(params.cluster-name)
        - name: provision-cluster
          value: true
      taskRef:
        kind: Task
        name: provision-osd-gcp
      runAfter:
        - ocm-login
      workspaces:
        - name: shared-workspace
    - name: wait-till-osd-is-ready
      params:
        - name: cluster-id
          value: $(tasks.provision-osd-gcp.results.cluster-id)
      taskRef:
        kind: Task
        name: wait-till-osd-is-ready
      runAfter:
        - provision-osd-gcp
      workspaces:
        - name: shared-workspace
    - name: get-osd-credentials
      params:
        - name: cluster-id
          value: $(tasks.provision-osd-gcp.results.cluster-id)
        - name: provision-cluster
          value: true
      taskRef:
        kind: Task
        name: get-osd-credentials
      runAfter:
        - wait-till-osd-is-ready
      workspaces:
        - name: shared-workspace
    - name: wait-for-valid-certificates
      params:
        - name: console-url
          value: $(tasks.get-osd-credentials.results.console-url)
        - name: api-url
          value: $(tasks.get-osd-credentials.results.kube-api)
      taskRef:
        kind: Task
        name: wait-for-valid-certificates
      runAfter:
        - get-osd-credentials
      workspaces:
        - name: shared-workspace
  workspaces:
    - name: shared-workspace
