apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: clone
spec:
  steps:
  - name: clone
    args:
      - >-
        git
        clone 
        -b main 
        --depth '1' 
        https://github.com/Kuadrant/helm-charts-olm.git
        $(workspaces.shared-workspace.path)/kuadrant-helm-install
    command:
      - /bin/bash
      - -c
    computeResources:
      limits:
        cpu: 250m
        memory: 128Mi
    image: quay.io/kuadrant/testsuite-pipelines-tools:latest
    imagePullPolicy: Always
  workspaces:
  - name: shared-workspace
