apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: helm-install
spec:
  params:
    - description: Kuadrant image url
      name: index-image
      type: string
    - description: Kuadrant image channel. Can be 'preview' for nightlies and 'stable' for releases
      name: channel
      type: string
    - description: A 'ossm3' for Openshift Service mesh v3, 'ocp' for installing on Openshift 4.19+
      name: istio-provider
      type: string
    - description: GatewayAPI CRD version. v1.0.0, v1.1.0, v1.2.1, v1.3.0 available; Leave empty if installing on ocp4.19+
      name: gateway-crd
      type: string
    - description: Keycloak subscription channel
      name: keycloak-channel
      type: string
    - description: Path to workspace kubeconfig
      name: kubeconfig-path
      type: string
    - description: Kuadrant operator name. 'kuadrant-operator' or 'rhcl-operator'
      name: operator-name
      type: string
    - description: Extensions binary image
      name: extensions-binary-image
      type: string
    - description: Additional flags for helm install command, example '--set=kuadrant.installPlanApproval=Manual --set=kuadrant.startingCSV=kuadrant-operator.v1.2.0'"
      name: additional-helm-flags
      type: string
    - description: Additional flags for tools helm, example '--set=tools.keycloak.keycloakProvider=deployment --set=tools.valkey.enable=false'"
      name: additional-helm-tools-flags
      type: string
  steps:
  - name: helm-install-tools-operators
    script: >
      helm install -n=default
      --repo https://kuadrant.io/helm-charts-olm
      $(params.additional-helm-tools-flags)
      --wait --debug
      tools-operators
      tools-operators
    env:
      - name: KUBECONFIG
        value: $(params.kubeconfig-path)
    image: quay.io/kuadrant/testsuite-pipelines-tools:latest
    imagePullPolicy: Always
  - name: helm-install-tools-instances
    script: >
      helm install -n=default
      --repo https://kuadrant.io/helm-charts-olm
      $(params.additional-helm-tools-flags)
      --wait --debug --timeout=10m0s
      tools-instances
      tools-instances
    env:
      - name: KUBECONFIG
        value: $(params.kubeconfig-path)
    image: quay.io/kuadrant/testsuite-pipelines-tools:latest
    imagePullPolicy: Always
  - name: helm-install-operators
    script: >
      helm install -n=default
      --repo https://kuadrant.io/helm-charts-olm
      --values=/mount/values-additional-manifests/additionalManifests.yaml
      --set=kuadrant.indexImage="$(params.index-image)"
      --set=kuadrant.channel="$(params.channel)"
      --set=kuadrant.operatorName="$(params.operator-name)"
      --set=kuadrant.extensionsBinaryImage="$(params.extensions-binary-image)"
      --set=istio.istioProvider="$(params.istio-provider)"
      --set=gatewayAPI.version="$(params.gateway-crd)"
      --set=tools.keycloak.operator.channel="$(params.keycloak-channel)"
      --set=tools.enabled=true
      $(params.additional-helm-flags)
      --wait --debug
      kuadrant-operators
      kuadrant-operators
    volumeMounts:
      - mountPath: /mount/values-additional-manifests
        name: values-additional-manifests
    env:
      - name: KUBECONFIG
        value: $(params.kubeconfig-path)
    image: quay.io/kuadrant/testsuite-pipelines-tools:latest
    imagePullPolicy: Always
  - name: helm-install-instances
    script: >
      helm install -n=default
      --repo https://kuadrant.io/helm-charts-olm
      --values=/mount/values-additional-manifests/additionalManifests.yaml
      --set=kuadrant.indexImage="$(params.index-image)"
      --set=kuadrant.channel="$(params.channel)"
      --set=kuadrant.operatorName="$(params.operator-name)"
      --set=istio.istioProvider="$(params.istio-provider)"
      --set=gatewayAPI.version="$(params.gateway-crd)"
      --set=tools.keycloak.operator.channel="$(params.keycloak-channel)"
      --set=tools.enabled=true
      $(params.additional-helm-flags)
      --wait --debug
      kuadrant-instances
      kuadrant-instances
    volumeMounts:
      - mountPath: /mount/values-additional-manifests
        name: values-additional-manifests
    env:
      - name: KUBECONFIG
        value: $(params.kubeconfig-path)
    image: quay.io/kuadrant/testsuite-pipelines-tools:latest
    imagePullPolicy: Always
  volumes:
    - secret:
        secretName: values-additional-manifests
      name: values-additional-manifests
  workspaces:
  - name: shared-workspace
