apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: helm-install
spec:
  params:
    - description: Kuadrant image url
      name: index-image
      type: string
    - description: Kuadrant image channel. Can be 'preview' for nightlies and 'stable' for releases
      name: channel
      type: string
    - description: A 'ossm3' for Openshift Service mesh v3, 'ocp' for installing on Openshift 4.19+
      name: istio-provider
      type: string
    - description: GatewayAPI CRD version. Leave empty if installing on ocp4.19+
      name: gateway-crd
      type: string
    - description: Keycloak subscription channel
      name: keycloak-channel
      type: string
    - description: Path to workspace kubeconfig
      name: kubeconfig-path
      type: string
    - description: Kuadrant operator name. 'kuadrant-operator' or 'rhcl-operator'
      name: operator-name
      type: string
    - description: Additional flags for helm install command, example '--set=kuadrant.installPlanApproval=Manual --set=kuadrant.startingCSV=kuadrant-operator.v1.2.0'"
      name: helm-install-flags
      type: string
  steps:
  - name: helm-install-operators
    script: |
      helm install -n=default \
      --values=$(workspaces.shared-workspace.path)/kuadrant-helm-install/values.yaml \
      --values=/mount/values-additional-manifests/additionalManifests.yaml \
      --set=kuadrant.indexImage=$(params.index-image) \
      --set=kuadrant.channel=$(params.channel) \
      --set=kuadrant.operatorName=$(params.operator-name) \
      --set=istio.istioProvider=$(params.istio-provider) \
      --set=gatewayAPI.version=$(params.gateway-crd) \
      --set=tools.keycloak.operator.channel=$(params.keycloak-channel) \
      --set=tools.enabled=true \
      $(params.helm-install-flags) \
      --wait --debug \
      kuadrant-operators \
      $(workspaces.shared-workspace.path)/kuadrant-helm-install/operators/
    volumeMounts:
      - mountPath: /mount/values-additional-manifests
        name: values-additional-manifests
    env:
      - name: KUBECONFIG
        value: $(params.kubeconfig-path)
    image: quay.io/kuadrant/testsuite-pipelines-tools:latest
    imagePullPolicy: Always
  - name: helm-install-instances
    script: |
      helm install -n=default \
      --values=$(workspaces.shared-workspace.path)/kuadrant-helm-install/values.yaml \
      --values=/mount/values-additional-manifests/additionalManifests.yaml \
      --set=kuadrant.indexImage=$(params.index-image) \
      --set=kuadrant.channel=$(params.channel) \
      --set=kuadrant.operatorName=$(params.operator-name) \
      --set=istio.istioProvider=$(params.istio-provider) \
      --set=gatewayAPI.version=$(params.gateway-crd) \
      --set=tools.keycloak.operator.channel=$(params.keycloak-channel) \
      --set=tools.enabled=true \
      $(params.helm-install-flags) \
      --wait --debug --timeout=10m0s \
      kuadrant-instances \
      $(workspaces.shared-workspace.path)/kuadrant-helm-install/instances/
    volumeMounts:
      - mountPath: /mount/values-additional-manifests
        name: values-additional-manifests
    env:
      - name: KUBECONFIG
        value: $(params.kubeconfig-path)
    image: quay.io/kuadrant/testsuite-pipelines-tools:latest
    imagePullPolicy: Always
  volumes:
    - secret:
        secretName: values-additional-manifests
      name: values-additional-manifests
  workspaces:
  - name: shared-workspace
