---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  deployment: kuadrant-qe-pipeline

resources:
  - run-tests-task.yaml
  - upload-test-results-task.yaml
  - pipeline.yaml

